package com.example.cia3.ui.theme

import androidx.compose.ui.graphics.Color

// ══════════════════════════════════════
//  PINK (default)
// ══════════════════════════════════════
val PinkPrimary = Color(0xFFE91E63)
val PinkPrimaryLight = Color(0xFFF48FB1)
val PinkPrimaryDark = Color(0xFFC2185B)
val PinkSecondary = Color(0xFFF06292)
val PinkSecondaryLight = Color(0xFFF8BBD0)
val PinkBackground = Color(0xFFFFF0F5)
val PinkSurface = Color(0xFFFFFFFF)
val PinkSurfaceVariant = Color(0xFFFCE4EC)
val PinkOnPrimary = Color(0xFFFFFFFF)
val PinkOnSecondary = Color(0xFFFFFFFF)
val PinkOnBackground = Color(0xFF2D1B1E)
val PinkOnSurface = Color(0xFF2D1B1E)
val PinkOnSurfaceVariant = Color(0xFF6D4C5A)
val PinkOutline = Color(0xFFF8BBD0)
val PinkOutlineVariant = Color(0xFFFCE4EC)
val PinkError = Color(0xFFBA1A1A)
val PinkOnError = Color(0xFFFFFFFF)
val PinkErrorContainer = Color(0xFFFFDAD6)
val PinkCardBackground = Color(0xFFFFF5F8)
val PinkDivider = Color(0xFFF8BBD0)
val PinkFabBackground = Color(0xFFE91E63)
val PinkChip = Color(0xFFFCE4EC)

// Dark Pink
val DarkPinkPrimary = Color(0xFFF48FB1)
val DarkPinkOnPrimary = Color(0xFF4A0028)
val DarkPinkPrimaryContainer = Color(0xFF6D1043)
val DarkPinkOnPrimaryContainer = Color(0xFFFFD9E3)
val DarkPinkSecondary = Color(0xFFF8BBD0)
val DarkPinkOnSecondary = Color(0xFF4B1D2D)
val DarkPinkBackground = Color(0xFF1A1114)
val DarkPinkSurface = Color(0xFF1A1114)
val DarkPinkSurfaceVariant = Color(0xFF3D2832)
val DarkPinkOnSurface = Color(0xFFEFDDE2)
val DarkPinkOnSurfaceVariant = Color(0xFFD6BFC8)
val DarkPinkOutline = Color(0xFF9D8A92)

// ══════════════════════════════════════
//  BLUE
// ══════════════════════════════════════
val BluePrimary = Color(0xFF1976D2)
val BluePrimaryLight = Color(0xFF90CAF9)
val BluePrimaryDark = Color(0xFF0D47A1)
val BlueSecondary = Color(0xFF42A5F5)
val BlueSecondaryLight = Color(0xFFBBDEFB)
val BlueBackground = Color(0xFFF0F5FF)
val BlueSurfaceVariant = Color(0xFFE3F2FD)
val BlueOnSurfaceVariant = Color(0xFF3B5068)
val BlueOutline = Color(0xFFBBDEFB)
val BlueCardBackground = Color(0xFFF5F9FF)
val BlueChip = Color(0xFFE3F2FD)

val DarkBluePrimary = Color(0xFF90CAF9)
val DarkBlueOnPrimary = Color(0xFF002952)
val DarkBluePrimaryContainer = Color(0xFF0D47A1)
val DarkBlueOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkBlueSecondary = Color(0xFFBBDEFB)
val DarkBlueOnSecondary = Color(0xFF1B3048)
val DarkBlueBackground = Color(0xFF111418)
val DarkBlueSurface = Color(0xFF111418)
val DarkBlueSurfaceVariant = Color(0xFF283240)
val DarkBlueOnSurface = Color(0xFFDDE4EF)
val DarkBlueOnSurfaceVariant = Color(0xFFBFC8D4)
val DarkBlueOutline = Color(0xFF8A929D)

// ══════════════════════════════════════
//  GREEN
// ══════════════════════════════════════
val GreenPrimary = Color(0xFF388E3C)
val GreenPrimaryLight = Color(0xFFA5D6A7)
val GreenPrimaryDark = Color(0xFF1B5E20)
val GreenSecondary = Color(0xFF66BB6A)
val GreenSecondaryLight = Color(0xFFC8E6C9)
val GreenBackground = Color(0xFFF0FFF0)
val GreenSurfaceVariant = Color(0xFFE8F5E9)
val GreenOnSurfaceVariant = Color(0xFF3D5B3E)
val GreenOutline = Color(0xFFC8E6C9)
val GreenCardBackground = Color(0xFFF5FFF5)
val GreenChip = Color(0xFFE8F5E9)

val DarkGreenPrimary = Color(0xFFA5D6A7)
val DarkGreenOnPrimary = Color(0xFF003910)
val DarkGreenPrimaryContainer = Color(0xFF1B5E20)
val DarkGreenOnPrimaryContainer = Color(0xFFD1F5D3)
val DarkGreenSecondary = Color(0xFFC8E6C9)
val DarkGreenOnSecondary = Color(0xFF1D3B1E)
val DarkGreenBackground = Color(0xFF111814)
val DarkGreenSurface = Color(0xFF111814)
val DarkGreenSurfaceVariant = Color(0xFF283D2A)
val DarkGreenOnSurface = Color(0xFFDDEFDE)
val DarkGreenOnSurfaceVariant = Color(0xFFBFCCC0)
val DarkGreenOutline = Color(0xFF8A9D8B)

// ══════════════════════════════════════
//  RED
// ══════════════════════════════════════
val RedPrimary = Color(0xFFD32F2F)
val RedPrimaryLight = Color(0xFFEF9A9A)
val RedPrimaryDark = Color(0xFFB71C1C)
val RedSecondary = Color(0xFFEF5350)
val RedSecondaryLight = Color(0xFFFFCDD2)
val RedBackground = Color(0xFFFFF0F0)
val RedSurfaceVariant = Color(0xFFFFEBEE)
val RedOnSurfaceVariant = Color(0xFF6B3B3B)
val RedOutline = Color(0xFFFFCDD2)
val RedCardBackground = Color(0xFFFFF5F5)
val RedChip = Color(0xFFFFEBEE)

val DarkRedPrimary = Color(0xFFEF9A9A)
val DarkRedOnPrimary = Color(0xFF520000)
val DarkRedPrimaryContainer = Color(0xFFB71C1C)
val DarkRedOnPrimaryContainer = Color(0xFFFFD9D9)
val DarkRedSecondary = Color(0xFFFFCDD2)
val DarkRedOnSecondary = Color(0xFF4B1D1D)
val DarkRedBackground = Color(0xFF1A1111)
val DarkRedSurface = Color(0xFF1A1111)
val DarkRedSurfaceVariant = Color(0xFF3D2828)
val DarkRedOnSurface = Color(0xFFEFDDDD)
val DarkRedOnSurfaceVariant = Color(0xFFD6BFBF)
val DarkRedOutline = Color(0xFF9D8A8A)

// ══════════════════════════════════════
//  PURPLE
// ══════════════════════════════════════
val PurplePrimary = Color(0xFF7B1FA2)
val PurplePrimaryLight = Color(0xFFCE93D8)
val PurplePrimaryDark = Color(0xFF4A148C)
val PurpleSecondary = Color(0xFFAB47BC)
val PurpleSecondaryLight = Color(0xFFE1BEE7)
val PurpleBackground = Color(0xFFF8F0FF)
val PurpleSurfaceVariant = Color(0xFFF3E5F5)
val PurpleOnSurfaceVariant = Color(0xFF5B3D68)
val PurpleOutline = Color(0xFFE1BEE7)
val PurpleCardBackground = Color(0xFFFCF5FF)
val PurpleChip = Color(0xFFF3E5F5)

val DarkPurplePrimary = Color(0xFFCE93D8)
val DarkPurpleOnPrimary = Color(0xFF380050)
val DarkPurplePrimaryContainer = Color(0xFF4A148C)
val DarkPurpleOnPrimaryContainer = Color(0xFFEED9F5)
val DarkPurpleSecondary = Color(0xFFE1BEE7)
val DarkPurpleOnSecondary = Color(0xFF3B1D48)
val DarkPurpleBackground = Color(0xFF161118)
val DarkPurpleSurface = Color(0xFF161118)
val DarkPurpleSurfaceVariant = Color(0xFF352840)
val DarkPurpleOnSurface = Color(0xFFE8DDEF)
val DarkPurpleOnSurfaceVariant = Color(0xFFCDBFD6)
val DarkPurpleOutline = Color(0xFF968A9D)